#!/usr/bin/env bash

set -e

echo "-----> Testing searls-auth gem"
bundle exec rake

echo "-----> Testing example/simple_app"
cd example/simple_app
./script/test
cd ../..

echo "-----> Looks good! 🪩"
