name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.4']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      # Example app stuff
      - name: Cache gems for example/simple_app
        uses: actions/cache@v4
        with:
          path: example/simple_app/vendor/bundle
          key: ${{ runner.os }}-gems-simple_app-${{ hashFiles('example/simple_app/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-simple_app-

      - name: Bundle install for example/simple_app
        run: |
          cd example/simple_app
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'node'

      - name: Cache Yarn v1 global cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('example/simple_app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - name: Install yarn dependencies in example/simple_app
        run: |
          cd example/simple_app
          yarn install --frozen-lockfile --immutable

      - name: Cache Playwright Chromium browser
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('example/simple_app/yarn.lock') }}

      - name: Install Playwright Chromium browser (with deps)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          cd example/simple_app
          yarn run playwright install --with-deps chromium

      - name: Install Playwright Chromium browser deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: |
          cd example/simple_app
          yarn run playwright install-deps chromium

      - name: Run the default task
        run: |
          script/setup_ci
          script/test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
